"""Initial Migration

Revision ID: 776765d0bb81
Revises: f754084f1925
Create Date: 2021-06-09 22:48:17.265308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776765d0bb81'
down_revision = 'f754084f1925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
